spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jys?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


pagehelper :
  helperDialect : mysql
  reasonable : true
  supportMethodsArguments : true
  params : count=countSql

mybatis:
  mapper-locations: classpath:com/gunn/jys/mapper/xml/*.xml

#mappers
mapper :
  mappers :
  not-empty : false
  identity : MYSQL

